spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/beatflow_analytics
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: beatflow-analytics-v2

catalog:
  base-url: http://localhost:8182

app:
  public-base-url: https://beatflow.akurilo.com
  cors:
    allowedOrigins:
      - http://localhost:5173
