spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/beatflow_auth
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

app:
  cookies:
    secure: true
  cors:
    allowedOrigins:
      - https://beatflow.akurilo.com
      - http://localhost:3000
      - http://localhost:5173
